# -*- coding: utf-8 -*-
"""Task1Attempt2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVh_bX545NSfRLACRnmxbUfqinv4kK5D
"""

# 1. Install dependencies
# !pip install -q transformers accelerate torchvision Pillow safetensors

"""# Only Once per runtime"""

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')  # If needed for POS tagging
nltk.download('wordnet')  # If you're doing any lemmatizing later

# 2. Import libraries
from PIL import Image
import torch
from transformers import BlipProcessor, BlipForConditionalGeneration
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
import string

# 3. Load BLIP-2 model
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large").to("cuda")

"""Either Use t5 or keybert for title generation"""

from transformers import pipeline

summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")

def summarize_title_t5(desc):
    summary = summarizer(desc, max_length=10, min_length=3, do_sample=False)[0]["summary_text"]
    return summary.title()

# !pip install keybert

from keybert import KeyBERT

kw_model = KeyBERT()

def summarize_title_keybert(desc):
    keywords = kw_model.extract_keywords(desc, keyphrase_ngram_range=(1, 2), stop_words='english', top_n=1)
    return keywords[0][0].title() if keywords else desc.title()

def clean_summarized_title(summary):
    words = summary.strip().split()
    important_words = [w for w in words if w.lower() not in ['there', 'is', 'a', 'an', 'the']]
    return ' '.join(important_words[:4]).title()

def generate_image_metadata(image_path):
    image = Image.open(image_path).convert('RGB')

    inputs = processor(images=image, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=60)

    raw_caption = processor.decode(out[0], skip_special_tokens=True)
    clean_caption = raw_caption.strip().capitalize()

    # Smart title: first meaningful part of the sentence (if possible)
    # title = clean_caption.split(",")[0].split(".")[0]
    # title_ids = model.generate(**inputs, max_new_tokens=6)
    # title = processor.decode(title_ids[0], skip_special_tokens=True).strip().capitalize()

    # summary = summarizer(desc, max_length=10, min_length=3, do_sample=False)[0]["summary_text"]
    # title = clean_summarized_title(summary)
    title = summarize_title_t5(clean_caption)

    # Clean tags: remove stopwords, short words, duplicates
    from nltk.corpus import stopwords
    import string

    stop_words = set(stopwords.words('english'))
    words = clean_caption.translate(str.maketrans('', '', string.punctuation)).split()
    tags = list(set(
        word.lower() for word in words
        if word.lower() not in stop_words and len(word) > 3
    ))

    return {
        "title": title,
        "description": clean_caption,
        "tags": tags
    }

from google.colab import files

uploaded = files.upload()
image_path = list(uploaded.keys())[0]

metadata = generate_image_metadata(image_path)
print("📝 Title:", metadata["title"])
print("📜 Description:", metadata["description"])
print("🏷️ Tags:", metadata["tags"])

